##Spring Configuration
server:
  port: 8080
spring:
  application:
    name: Users
  devtools:
    add-properties: false
  r2dbc:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: admin
  profiles:
    include:
